### ISSUE TITLE
Clone, install, build, start?  Fail.

### ISSUE THREAD

**Issue by StoneCypher** [githubnext/blocks-template#42]
Hiya.  Super excited to try this.  Windows 10 up to date, npm, running from git bash.  Started from a fork of your repo, otherwise unaltered.

* `git clone` works
* `npm install` works
* `npm build` works
* `npm start` fails three ways
    1. On starting, announces that it cannot resolve `react-dom/client` (1)
    2. Immediately replaces that message with a cullscreen clear, where `vite` yields a failure about being unable to resolve the same library (2)
    3. Yields an in-browser error regarding this when hit in browser (3)

----

1:

![image](https://user-images.githubusercontent.com/77482/201532968-07413ccd-3f78-4a9c-a0ff-51b05a7d688b.png)

----

2:

![image](https://user-images.githubusercontent.com/77482/201532994-4ef7cd40-6e55-4fb9-a7b9-0f10a6d266b6.png)

----

3:

![image](https://user-images.githubusercontent.com/77482/201533017-3b2d35f3-587b-4236-b946-b1498213b865.png)

----

I tried manually installing react-dom as a dev dep; didn't help.

**Comment by StoneCypher** [comment]
Confirmed same behavior in dos console and powershell

**Comment by StoneCypher** [comment]
Confirmed same behavior when switching to `yarn`, even when removing `yarn-lock` and `package-lock` then reinstalling as from #28 first

**Comment by StoneCypher** [comment]
Tried to build an alpine image and build in there.

If you mount the existing directory, esbuild complains that it was built for a different platform

If you try to install internally, esbuild complains that it can't figure out what platform it is

**Comment by StoneCypher** [comment]
Set up an actual Ubuntu machine.

Works as expected there 😢

**Comment by idan** [comment]
Fixed in https://github.com/githubnext/blocks-template/commit/246887e28444c326185fa8e1fb958aed1d0ce29b!

The underlying issue was that `@primer/react` expressed a peer dep of react 17.x, whereas everything else we use relies on react 18. The way yarn writes dependencies to disk was fine (it installs react 18) but npm would "vendor" in the node_modules for primer/react, which included react 17. Subsequent attempts to load react-dom/client would fail.

Thank you for the bug report!
